# Generated by Django 4.2.3 on 2023-07-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sorvete_mesa_alter_sorvete_cobertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorvete',
            name='salgado',
            field=models.CharField(choices=[('', ''), ('Coxinha', 'Coxinha'), ('Risole', 'Risole'), ('Empada', 'Empada')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sorvete',
            name='cobertura',
            field=models.CharField(choices=[('', ''), ('Chocolate', 'Chocolate'), ('Morango', 'Morango'), ('Caramelo', 'Caramelo'), ('Leite Condensado', 'Leite condensado')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sorvete',
            name='mesa',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='sorvete',
            name='sabor',
            field=models.CharField(choices=[('', ''), ('Açaí', 'Açaí'), ('Cupuaçu', 'Cupuaçu')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sorvete',
            name='tamanho',
            field=models.CharField(choices=[('', ''), ('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande'), ('Barca', 'Barca')], default='', max_length=10),
        ),
    ]
